// Compile hand-editable theme YAML (frontend/themes/*.yaml) into a committed
// TypeScript module (src/lib/theme/themes.generated.ts). Run via `npm run themes:build`.
//
// This is the ONLY step that reads YAML: the app, tests and `vite build` import the
// committed .ts, so npm ci / build / vitest need no YAML dependency. `palette.<key>`
// strings in tokens/graph are resolved to their hex here so the output is fully inlined.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { parse } from 'yaml';

const here = dirname(fileURLToPath(import.meta.url));
const themesDir = join(here, '..', 'themes');
const outFile = join(here, '..', 'src', 'lib', 'theme', 'themes.generated.ts');

// Resolve any "palette.<key>" reference against the theme's palette ramp.
function resolveRefs(node, palette) {
  if (typeof node === 'string') {
    if (node.startsWith('palette.')) {
      const key = node.slice('palette.'.length);
      if (!(key in palette)) throw new Error(`Unknown palette reference: ${node}`);
      return palette[key];
    }
    return node;
  }
  if (Array.isArray(node)) return node.map((n) => resolveRefs(n, palette));
  if (node && typeof node === 'object') {
    return Object.fromEntries(Object.entries(node).map(([k, v]) => [k, resolveRefs(v, palette)]));
  }
  return node;
}

function loadTheme(file) {
  const raw = parse(readFileSync(join(themesDir, file), 'utf8'));
  const palette = raw.palette ?? {};
  return {
    id: raw.id,
    name: raw.name,
    mode: raw.mode,
    temperature: raw.temperature,
    tokens: resolveRefs(raw.tokens, palette),
    graph: resolveRefs(raw.graph, palette),
  };
}

const files = readdirSync(themesDir).filter((f) => f.endsWith('.yaml')).sort();
const themes = files.map(loadTheme);

const banner =
  '// GENERATED by scripts/build-themes.mjs from frontend/themes/*.yaml — DO NOT EDIT.\n' +
  '// Edit the YAML source and run `npm run themes:build`.\n';
const body =
  `import type { Theme } from './types';\n\n` +
  `export const bundledThemes: Theme[] = ${JSON.stringify(themes, null, 2)};\n`;

writeFileSync(outFile, banner + '\n' + body);
process.stdout.write(`Wrote ${themes.length} theme(s) to ${outFile}\n`);
