"""Squashed baseline: the complete PaRacORD schema as of revision 0067 (S-batch item 4)

This single migration replaces the historical chain 0001…0067 (68 files). It keeps the SAME
revision id as the old head, so:

* an EXISTING database stamped ``0067_citing_cap_ai_threshold`` (the oldest supported deployment
  floor, owner decision 2026-07-13) sees itself at head and nothing runs;
* a FRESH database gets the entire current schema in one step.

Schema source of truth: ``Base.metadata.create_all`` (the ORM models) plus the deliberately
off-ORM DDL the old chain added — the pgvector extension, the ``embeddings.vector_pg`` /
``work_chunks.vec_*`` vector columns with their HNSW indexes, the partial unique indexes on
``works.doi`` / ``works.arxiv_base_id`` — and the embedding-model registry seed rows (from 0036).
Equality with the old chain's schema is verified by diffing ``pg_dump --schema-only`` outputs
(see the 2026-07-13 handoff); constraint/index names are preserved so future migrations can
reference them on both old and fresh databases.

Older backups: none exist past-floor by owner statement; the logical backup system
(``services/backup.py``) restores by column-name intersection and does not depend on the
migration chain.

Revision ID: 0067_citing_cap_ai_threshold
Revises: None
Create Date: 2026-07-13 (squashed)
"""

from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = "0067_citing_cap_ai_threshold"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Embedding-model registry seed (carried over from 0036): the two built-in pgvector-backed models.
_REGISTRY_SEED = (
    (
        "minilm",
        "st:sentence-transformers/all-MiniLM-L6-v2",
        "sentence_transformers",
        "sentence-transformers/all-MiniLM-L6-v2",
        384,
        "vec_minilm",
    ),
    (
        "nomic",
        "ollama:nomic-embed-text:latest",
        "ollama",
        "nomic-embed-text:latest",
        768,
        "vec_nomic",
    ),
)


def upgrade() -> None:
    """Create the full schema AS OF revision 0067 (fresh installs only).

    FROZEN static DDL (alembic-autogenerated from the models at squash time, then pinned): it must
    NEVER be regenerated from live models — later schema changes belong in later migrations, and a
    moving baseline would collide with their add_column/create_index statements on fresh installs.
    """
    bind = op.get_bind()
    is_postgres = bind.dialect.name == "postgresql"
    if is_postgres:
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    _create_frozen_schema()

    if is_postgres:
        # Off-ORM pgvector columns + ANN indexes (kept out of the models so SQLite tests work).
        op.execute("ALTER TABLE embeddings ADD COLUMN IF NOT EXISTS vector_pg vector")
        op.execute("ALTER TABLE work_chunks ADD COLUMN IF NOT EXISTS vec_minilm vector(384)")
        op.execute("ALTER TABLE work_chunks ADD COLUMN IF NOT EXISTS vec_nomic vector(768)")
        op.execute(
            "CREATE INDEX IF NOT EXISTS ix_work_chunks_vec_minilm ON work_chunks "
            "USING hnsw (vec_minilm vector_cosine_ops)"
        )
        op.execute(
            "CREATE INDEX IF NOT EXISTS ix_work_chunks_vec_nomic ON work_chunks "
            "USING hnsw (vec_nomic vector_cosine_ops)"
        )
        # Partial unique identifier indexes (NULLs exempt) — kept off-ORM for SQLite compatibility.
        op.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS uq_works_doi ON works (doi) WHERE doi IS NOT NULL"
        )
        op.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS uq_works_arxiv_base_id ON works (arxiv_base_id) "
            "WHERE arxiv_base_id IS NOT NULL"
        )

        # --- Parity fix-ups vs the historical chain (verified by pg_dump diff) ---------------
        # Server-side column defaults the old chain declared but the ORM keeps Python-side.
        # They matter for raw INSERTs (data migrations, the logical backup restore).
        for stmt in (
            "ALTER TABLE agent_files ALTER COLUMN import_action SET DEFAULT 'index_only'",
            "ALTER TABLE agent_files ALTER COLUMN processing_state SET DEFAULT 'indexed'",
            "ALTER TABLE agent_files ALTER COLUMN size_bytes SET DEFAULT 0",
            "ALTER TABLE agent_files ALTER COLUMN teleport_policy SET DEFAULT 'ask'",
            "ALTER TABLE agent_files ALTER COLUMN teleport_status SET DEFAULT 'none'",
            "ALTER TABLE audit_events ALTER COLUMN created_at SET DEFAULT now()",
            "ALTER TABLE embedding_model_registry ALTER COLUMN active SET DEFAULT true",
            "ALTER TABLE file_segments ALTER COLUMN confidence SET DEFAULT 100",
            "ALTER TABLE file_segments ALTER COLUMN created_at SET DEFAULT now()",
            "ALTER TABLE file_segments ALTER COLUMN created_by SET DEFAULT 'system'",
            "ALTER TABLE file_segments ALTER COLUMN segment_type SET DEFAULT 'full_file'",
            "ALTER TABLE file_work_links ALTER COLUMN confidence SET DEFAULT 100",
            "ALTER TABLE file_work_links ALTER COLUMN created_at SET DEFAULT now()",
            "ALTER TABLE file_work_links ALTER COLUMN relationship_type SET DEFAULT 'primary'",
            "ALTER TABLE file_work_links ALTER COLUMN user_confirmed SET DEFAULT false",
            "ALTER TABLE file_work_links ALTER COLUMN warning_state SET DEFAULT 'none'",
            "ALTER TABLE files ALTER COLUMN created_at SET DEFAULT now()",
            "ALTER TABLE files ALTER COLUMN status SET DEFAULT 'available'",
            "ALTER TABLE files ALTER COLUMN text_layer_quality SET DEFAULT 'unknown'",
            "ALTER TABLE import_batches ALTER COLUMN created_at SET DEFAULT now()",
            "ALTER TABLE import_batches ALTER COLUMN status SET DEFAULT 'queued'",
            "ALTER TABLE locations ALTER COLUMN created_at SET DEFAULT now()",
            "ALTER TABLE locations ALTER COLUMN is_available SET DEFAULT true",
            "ALTER TABLE locations ALTER COLUMN is_primary SET DEFAULT true",
            "ALTER TABLE rack_shelves ALTER COLUMN added_at SET DEFAULT now()",
            "ALTER TABLE racks ALTER COLUMN created_at SET DEFAULT now()",
            "ALTER TABLE racks ALTER COLUMN status SET DEFAULT 'active'",
            "ALTER TABLE racks ALTER COLUMN updated_at SET DEFAULT now()",
            "ALTER TABLE shelf_works ALTER COLUMN added_at SET DEFAULT now()",
            "ALTER TABLE shelves ALTER COLUMN created_at SET DEFAULT now()",
            "ALTER TABLE shelves ALTER COLUMN status SET DEFAULT 'active'",
            "ALTER TABLE shelves ALTER COLUMN updated_at SET DEFAULT now()",
            "ALTER TABLE sources ALTER COLUMN created_at SET DEFAULT now()",
            "ALTER TABLE sources ALTER COLUMN is_active SET DEFAULT true",
            "ALTER TABLE summaries ALTER COLUMN fallback SET DEFAULT false",
            "ALTER TABLE tag_links ALTER COLUMN created_at SET DEFAULT now()",
            "ALTER TABLE tags ALTER COLUMN created_at SET DEFAULT now()",
            "ALTER TABLE user_sessions ALTER COLUMN created_at SET DEFAULT now()",
            "ALTER TABLE users ALTER COLUMN created_at SET DEFAULT now()",
            "ALTER TABLE work_chunks ALTER COLUMN token_count SET DEFAULT 0",
            "ALTER TABLE work_versions ALTER COLUMN created_at SET DEFAULT now()",
            "ALTER TABLE work_versions ALTER COLUMN version_type SET DEFAULT 'unknown'",
            "ALTER TABLE works ALTER COLUMN created_at SET DEFAULT now()",
            "ALTER TABLE works ALTER COLUMN reading_status SET DEFAULT 'unread'",
            "ALTER TABLE works ALTER COLUMN updated_at SET DEFAULT now()",
            "ALTER TABLE works ALTER COLUMN user_confirmed SET DEFAULT false",
            "ALTER TABLE works ALTER COLUMN work_type SET DEFAULT 'unknown'",
            # Constraint names must match the historical chain so future migrations can
            # reference them on BOTH old and fresh databases.
            "ALTER TABLE agent_files RENAME CONSTRAINT agent_files_work_id_fkey TO fk_agent_files_work_id",
            "ALTER TABLE external_papers RENAME CONSTRAINT external_papers_resolved_work_id_fkey TO fk_external_papers_resolved_work_id",
            "ALTER TABLE locations RENAME CONSTRAINT locations_agent_id_fkey TO fk_locations_agent_id",
            "ALTER TABLE citation_mentions RENAME CONSTRAINT citation_mentions_citing_work_id_fkey TO fk_mentions_citing_work",
            "ALTER TABLE citation_mentions RENAME CONSTRAINT citation_mentions_reference_id_fkey TO fk_mentions_reference",
            "ALTER TABLE citation_mentions RENAME CONSTRAINT citation_mentions_resolved_cited_work_id_fkey TO fk_mentions_resolved_work",
            "ALTER TABLE citation_mentions RENAME CONSTRAINT citation_mentions_source_tei_id_fkey TO fk_mentions_source_tei",
            'ALTER TABLE "references" RENAME CONSTRAINT references_resolved_work_id_fkey TO fk_references_resolved_work',
            "ALTER TABLE works RENAME CONSTRAINT works_main_file_id_fkey TO fk_works_main_file_id",
            "ALTER TABLE works RENAME CONSTRAINT works_merged_into_id_fkey TO fk_works_merged_into_id",
            # A constraint the old chain added that the ORM never declared.
            "ALTER TABLE agent_enrollment_tokens ADD CONSTRAINT uq_agent_enrollment_token_hash UNIQUE (token_hash)",
            # The old chain declared this default on the quoted "references" table.
            "ALTER TABLE \"references\" ALTER COLUMN resolution_status SET DEFAULT 'unresolved'",
            # Strict index parity with the old chain: the models want these three indexes but the
            # chain never created them / created them differently — a fresh install must match the
            # oldest running deployment exactly so a FUTURE migration adding/altering them behaves
            # identically on both. (Follow-up: one migration adding the two missing indexes
            # everywhere, then these three statements can go.)
            "DROP INDEX IF EXISTS ix_agents_created_by_user_id",
            "DROP INDEX IF EXISTS ix_works_doi",
            "DROP INDEX IF EXISTS ix_agent_enrollment_tokens_token_hash",
            "CREATE INDEX ix_agent_enrollment_tokens_token_hash ON agent_enrollment_tokens (token_hash)",
        ):
            op.execute(stmt)

    now = datetime.now(UTC)
    registry = sa.table(
        "embedding_model_registry",
        sa.column("slug", sa.String),
        sa.column("model_name", sa.String),
        sa.column("provider", sa.String),
        sa.column("raw_model", sa.String),
        sa.column("dim", sa.Integer),
        sa.column("column_name", sa.String),
        sa.column("active", sa.Boolean),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(
        registry,
        [
            {
                "slug": slug,
                "model_name": model_name,
                "provider": provider,
                "raw_model": raw_model,
                "dim": dim,
                "column_name": column_name,
                "active": True,
                "created_at": now,
            }
            for slug, model_name, provider, raw_model, dim, column_name in _REGISTRY_SEED
        ],
    )


def downgrade() -> None:
    """Irreversible: this is the baseline (there is nothing before it)."""
    raise NotImplementedError("The squashed baseline cannot be downgraded")


def _create_frozen_schema() -> None:
    """The full schema at revision 0067 — pinned autogenerate output; do not regenerate."""
    op.create_table(
        "access_settings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("default_access_level", sa.String(length=16), nullable=True),
        sa.Column("default_shelf_id", sa.Uuid(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "agent_enrollment_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_by_agent_id", sa.Uuid(), nullable=True),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_enrollment_tokens_created_by_user_id"),
        "agent_enrollment_tokens",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_enrollment_tokens_token_hash"),
        "agent_enrollment_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_agent_enrollment_tokens_used_by_agent_id"),
        "agent_enrollment_tokens",
        ["used_by_agent_id"],
        unique=False,
    )
    op.create_table(
        "agents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("host_alias", sa.String(length=255), nullable=True),
        sa.Column(
            "capabilities",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("can_index", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("can_extract", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("can_teleport", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("can_be_requested", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("processing_visibility", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("server_status_visibility", sa.Boolean(), server_default="true", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agents_approved_by_user_id"), "agents", ["approved_by_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_agents_created_by_user_id"), "agents", ["created_by_user_id"], unique=False
    )
    op.create_index(op.f("ix_agents_name"), "agents", ["name"], unique=False)
    op.create_index(op.f("ix_agents_status"), "agents", ["status"], unique=False)
    op.create_index(op.f("ix_agents_token_hash"), "agents", ["token_hash"], unique=False)
    op.create_table(
        "ai_config",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("embedding_provider", sa.String(length=64), nullable=True),
        sa.Column("embedding_model", sa.String(length=255), nullable=True),
        sa.Column("summary_provider", sa.String(length=64), nullable=True),
        sa.Column("summary_model", sa.String(length=255), nullable=True),
        sa.Column("topic_backend", sa.String(length=64), nullable=True),
        sa.Column("topic_embedding_model", sa.String(length=255), nullable=True),
        sa.Column("ocr_backend", sa.String(length=64), nullable=True),
        sa.Column("ocr_language", sa.String(length=128), nullable=True),
        sa.Column("ollama_url", sa.String(length=512), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "annotations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("work_id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=True),
        sa.Column("version_id", sa.Uuid(), nullable=True),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column(
            "coordinates",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("selected_text", sa.Text(), nullable=True),
        sa.Column("annotation_type", sa.String(length=64), nullable=False),
        sa.Column("content_markdown", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_annotations_annotation_type"), "annotations", ["annotation_type"], unique=False
    )
    op.create_index(
        op.f("ix_annotations_created_by_user_id"),
        "annotations",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(op.f("ix_annotations_file_id"), "annotations", ["file_id"], unique=False)
    op.create_index(op.f("ix_annotations_page"), "annotations", ["page"], unique=False)
    op.create_index(op.f("ix_annotations_version_id"), "annotations", ["version_id"], unique=False)
    op.create_index(op.f("ix_annotations_work_id"), "annotations", ["work_id"], unique=False)
    op.create_table(
        "app_config",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("max_papers_per_page", sa.Integer(), server_default="500", nullable=False),
        sa.Column(
            "rate_limit_per_client_per_min", sa.Integer(), server_default="120", nullable=False
        ),
        sa.Column("rate_limit_global_per_min", sa.Integer(), server_default="600", nullable=False),
        sa.Column("max_batch_items", sa.Integer(), server_default="100", nullable=False),
        sa.Column("rq_worker_count", sa.Integer(), server_default="2", nullable=False),
        sa.Column("max_queue_len", sa.Integer(), server_default="1000", nullable=False),
        sa.Column("citing_papers_fetch_cap", sa.Integer(), server_default="1000", nullable=False),
        sa.Column("ai_scope_job_threshold", sa.Integer(), server_default="100", nullable=False),
        sa.Column("use_fuzzy_match_as_confirmed", sa.Boolean(), nullable=True),
        sa.Column("reference_rescan_on_startup", sa.Boolean(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_agent_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=True),
        sa.Column("entity_id", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=128), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_events_actor_agent_id"), "audit_events", ["actor_agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_actor_user_id"), "audit_events", ["actor_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_created_at"), "audit_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_event_type"), "audit_events", ["event_type"], unique=False
    )
    op.create_table(
        "default_grants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("target_type", sa.String(length=16), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("added_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("target_type", "target_id", name="uq_default_grant_target"),
    )
    op.create_table(
        "duplicate_candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("candidate_type", sa.String(length=64), nullable=False),
        sa.Column("entity_a_type", sa.String(length=64), nullable=False),
        sa.Column("entity_a_id", sa.Uuid(), nullable=False),
        sa.Column("entity_b_type", sa.String(length=64), nullable=False),
        sa.Column("entity_b_id", sa.Uuid(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column(
            "signals",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "candidate_type",
            "entity_a_type",
            "entity_a_id",
            "entity_b_type",
            "entity_b_id",
            name="uq_duplicate_candidate_pair",
        ),
    )
    op.create_index(
        op.f("ix_duplicate_candidates_candidate_type"),
        "duplicate_candidates",
        ["candidate_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_duplicate_candidates_entity_a_id"),
        "duplicate_candidates",
        ["entity_a_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_duplicate_candidates_entity_a_type"),
        "duplicate_candidates",
        ["entity_a_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_duplicate_candidates_entity_b_id"),
        "duplicate_candidates",
        ["entity_b_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_duplicate_candidates_entity_b_type"),
        "duplicate_candidates",
        ["entity_b_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_duplicate_candidates_resolved_by_user_id"),
        "duplicate_candidates",
        ["resolved_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_duplicate_candidates_status"), "duplicate_candidates", ["status"], unique=False
    )
    op.create_table(
        "embedding_model_registry",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("raw_model", sa.String(length=255), nullable=False),
        sa.Column("dim", sa.Integer(), nullable=False),
        sa.Column("column_name", sa.String(length=64), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("slug"),
    )
    op.create_index(
        op.f("ix_embedding_model_registry_model_name"),
        "embedding_model_registry",
        ["model_name"],
        unique=True,
    )
    op.create_table(
        "embeddings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("dim", sa.Integer(), nullable=False),
        sa.Column("vector", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_type", "entity_id", "model_name", name="uq_embedding_entity_model"
        ),
    )
    op.create_index(op.f("ix_embeddings_entity_id"), "embeddings", ["entity_id"], unique=False)
    op.create_index(op.f("ix_embeddings_entity_type"), "embeddings", ["entity_type"], unique=False)
    op.create_index(op.f("ix_embeddings_model_name"), "embeddings", ["model_name"], unique=False)
    op.create_table(
        "files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("mime_type", sa.String(length=128), nullable=True),
        sa.Column("original_filename", sa.Text(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("text_layer_quality", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("preview_text", sa.Text(), nullable=True),
        sa.Column("text_fingerprint", sa.String(length=255), nullable=True),
        sa.Column("extraction_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("extraction_attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_files_sha256"), "files", ["sha256"], unique=True)
    op.create_index(op.f("ix_files_status"), "files", ["status"], unique=False)
    op.create_index(op.f("ix_files_text_fingerprint"), "files", ["text_fingerprint"], unique=False)
    op.create_table(
        "import_roots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("alias", sa.String(length=255), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_import_roots_alias"), "import_roots", ["alias"], unique=True)
    op.create_index(
        op.f("ix_import_roots_created_by_user_id"),
        "import_roots",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_table(
        "import_staging_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("target_shelf_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_import_staging_batches_created_by_user_id"),
        "import_staging_batches",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_import_staging_batches_status"), "import_staging_batches", ["status"], unique=False
    )
    op.create_table(
        "metadata_assertions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("field_name", sa.String(length=128), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("selected_as_canonical", sa.Boolean(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_metadata_assertions_entity_id"), "metadata_assertions", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_metadata_assertions_entity_type"),
        "metadata_assertions",
        ["entity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metadata_assertions_field_name"),
        "metadata_assertions",
        ["field_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metadata_assertions_source"), "metadata_assertions", ["source"], unique=False
    )
    op.create_table(
        "racks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("access_level", sa.String(length=16), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_racks_created_by_user_id"), "racks", ["created_by_user_id"], unique=False
    )
    op.create_index(op.f("ix_racks_name"), "racks", ["name"], unique=False)
    op.create_index(op.f("ix_racks_status"), "racks", ["status"], unique=False)
    op.create_table(
        "raw_tei_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("work_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("tei_xml", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_raw_tei_documents_created_at"), "raw_tei_documents", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_raw_tei_documents_file_id"), "raw_tei_documents", ["file_id"], unique=False
    )
    op.create_index(
        op.f("ix_raw_tei_documents_source"), "raw_tei_documents", ["source"], unique=False
    )
    op.create_index(
        op.f("ix_raw_tei_documents_work_id"), "raw_tei_documents", ["work_id"], unique=False
    )
    op.create_table(
        "shelves",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("access_level", sa.String(length=16), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_shelves_created_by_user_id"), "shelves", ["created_by_user_id"], unique=False
    )
    op.create_index(op.f("ix_shelves_name"), "shelves", ["name"], unique=False)
    op.create_index(op.f("ix_shelves_status"), "shelves", ["status"], unique=False)
    op.create_table(
        "sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column("agent_id", sa.Uuid(), nullable=True),
        sa.Column("path_alias", sa.Text(), nullable=True),
        sa.Column("canonical_root_hash", sa.String(length=128), nullable=True),
        sa.Column(
            "config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sources_agent_id"), "sources", ["agent_id"], unique=False)
    op.create_index(
        op.f("ix_sources_canonical_root_hash"), "sources", ["canonical_root_hash"], unique=False
    )
    op.create_index(op.f("ix_sources_is_active"), "sources", ["is_active"], unique=False)
    op.create_index(op.f("ix_sources_name"), "sources", ["name"], unique=False)
    op.create_index(op.f("ix_sources_owner_user_id"), "sources", ["owner_user_id"], unique=False)
    op.create_index(op.f("ix_sources_path_alias"), "sources", ["path_alias"], unique=False)
    op.create_index(op.f("ix_sources_type"), "sources", ["type"], unique=False)
    op.create_table(
        "summaries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("summary_type", sa.String(length=64), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=True),
        sa.Column("prompt_version", sa.String(length=128), nullable=True),
        sa.Column("provider_requested", sa.String(length=64), nullable=True),
        sa.Column("provider_used", sa.String(length=64), nullable=True),
        sa.Column("fallback", sa.Boolean(), nullable=False),
        sa.Column("source_sections", sa.JSON(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("params", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_summaries_entity_id"), "summaries", ["entity_id"], unique=False)
    op.create_index(op.f("ix_summaries_entity_type"), "summaries", ["entity_type"], unique=False)
    op.create_index(op.f("ix_summaries_summary_type"), "summaries", ["summary_type"], unique=False)
    op.create_table(
        "tags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column("color", sa.String(length=32), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("parent_tag_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tags_name"), "tags", ["name"], unique=True)
    op.create_index(op.f("ix_tags_normalized_name"), "tags", ["normalized_name"], unique=True)
    op.create_table(
        "topic_assignments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("topic_model_id", sa.String(length=255), nullable=False),
        sa.Column("scope_type", sa.String(length=64), nullable=False),
        sa.Column("scope_id", sa.String(length=255), nullable=True),
        sa.Column("work_id", sa.Uuid(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_topic_assignments_scope_id"), "topic_assignments", ["scope_id"], unique=False
    )
    op.create_index(
        op.f("ix_topic_assignments_scope_type"), "topic_assignments", ["scope_type"], unique=False
    )
    op.create_index(
        op.f("ix_topic_assignments_topic_id"), "topic_assignments", ["topic_id"], unique=False
    )
    op.create_index(
        op.f("ix_topic_assignments_topic_model_id"),
        "topic_assignments",
        ["topic_model_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_topic_assignments_work_id"), "topic_assignments", ["work_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=128), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("is_bootstrap", sa.Boolean(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("papers_per_page", sa.Integer(), nullable=True),
        sa.Column("theme", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "web_find_allowed_hosts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_web_find_allowed_hosts_created_by_user_id"),
        "web_find_allowed_hosts",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_web_find_allowed_hosts_host"), "web_find_allowed_hosts", ["host"], unique=True
    )
    op.create_table(
        "web_find_settings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("download_policy", sa.String(length=32), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "custom_themes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("temperature", sa.String(length=16), nullable=False),
        sa.Column("yaml_source", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_custom_themes_slug"), "custom_themes", ["slug"], unique=True)
    op.create_table(
        "file_segments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("page_start", sa.Integer(), nullable=True),
        sa.Column("page_end", sa.Integer(), nullable=True),
        sa.Column("label", sa.String(length=255), nullable=True),
        sa.Column("segment_type", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_file_segments_file_id"), "file_segments", ["file_id"], unique=False)
    op.create_table(
        "groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("is_personal", sa.Boolean(), nullable=False),
        sa.Column("personal_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["personal_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_groups_name"), "groups", ["name"], unique=True)
    op.create_index(
        op.f("ix_groups_personal_user_id"), "groups", ["personal_user_id"], unique=False
    )
    op.create_table(
        "import_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("agent_id", sa.Uuid(), nullable=True),
        sa.Column("input_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column(
            "settings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "stats",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_import_batches_agent_id"), "import_batches", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_import_batches_created_by_user_id"),
        "import_batches",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_import_batches_input_type"), "import_batches", ["input_type"], unique=False
    )
    op.create_index(
        op.f("ix_import_batches_source_id"), "import_batches", ["source_id"], unique=False
    )
    op.create_index(op.f("ix_import_batches_status"), "import_batches", ["status"], unique=False)
    op.create_table(
        "import_staging_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=True),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "parsed",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("tei_xml", sa.Text(), nullable=True),
        sa.Column(
            "duplicates",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_work_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["batch_id"], ["import_staging_batches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_import_staging_items_batch_id"), "import_staging_items", ["batch_id"], unique=False
    )
    op.create_index(
        op.f("ix_import_staging_items_file_id"), "import_staging_items", ["file_id"], unique=False
    )
    op.create_index(
        op.f("ix_import_staging_items_sha256"), "import_staging_items", ["sha256"], unique=False
    )
    op.create_index(
        op.f("ix_import_staging_items_status"), "import_staging_items", ["status"], unique=False
    )
    op.create_table(
        "locations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("location_type", sa.String(length=64), nullable=False),
        sa.Column("display_path", sa.Text(), nullable=True),
        sa.Column("internal_uri", sa.Text(), nullable=True),
        sa.Column("path_alias", sa.Text(), nullable=True),
        sa.Column("agent_id", sa.Uuid(), nullable=True),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_locations_agent_id"), "locations", ["agent_id"], unique=False)
    op.create_index(op.f("ix_locations_file_id"), "locations", ["file_id"], unique=False)
    op.create_index(op.f("ix_locations_source_id"), "locations", ["source_id"], unique=False)
    op.create_table(
        "missing_work_decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("missing_key", sa.String(length=512), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "missing_key", name="uq_missing_decision_user_key"),
    )
    op.create_index(
        op.f("ix_missing_work_decisions_user_id"),
        "missing_work_decisions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "rack_shelves",
        sa.Column("rack_id", sa.Uuid(), nullable=False),
        sa.Column("shelf_id", sa.Uuid(), nullable=False),
        sa.Column("added_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["rack_id"], ["racks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["shelf_id"], ["shelves.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("rack_id", "shelf_id"),
    )
    op.create_index(
        op.f("ix_rack_shelves_added_by_user_id"), "rack_shelves", ["added_by_user_id"], unique=False
    )
    op.create_index(op.f("ix_rack_shelves_shelf_id"), "rack_shelves", ["shelf_id"], unique=False)
    op.create_table(
        "saved_filters",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("search_mode", sa.String(length=16), nullable=False),
        sa.Column("query_text", sa.Text(), nullable=True),
        sa.Column(
            "params",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_user_id", "name", name="uq_saved_filter_owner_name"),
    )
    op.create_index(
        op.f("ix_saved_filters_owner_user_id"), "saved_filters", ["owner_user_id"], unique=False
    )
    op.create_table(
        "tag_links",
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tag_id", "entity_type", "entity_id"),
    )
    op.create_index(
        op.f("ix_tag_links_created_by_user_id"), "tag_links", ["created_by_user_id"], unique=False
    )
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_sessions_expires_at"), "user_sessions", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_user_sessions_revoked_at"), "user_sessions", ["revoked_at"], unique=False
    )
    op.create_index(
        op.f("ix_user_sessions_token_hash"), "user_sessions", ["token_hash"], unique=True
    )
    op.create_index(op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False)
    op.create_table(
        "group_grants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("target_type", sa.String(length=16), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("added_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "target_type", "target_id", name="uq_group_grant_target"),
    )
    op.create_index(op.f("ix_group_grants_group_id"), "group_grants", ["group_id"], unique=False)
    op.create_table(
        "group_memberships",
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("added_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("group_id", "user_id"),
    )
    op.create_index(
        op.f("ix_group_memberships_user_id"), "group_memberships", ["user_id"], unique=False
    )
    op.create_table(
        "works",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canonical_title", sa.Text(), nullable=True),
        sa.Column("normalized_title", sa.Text(), nullable=True),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("doi", sa.String(length=255), nullable=True),
        sa.Column("arxiv_id", sa.String(length=64), nullable=True),
        sa.Column("arxiv_base_id", sa.String(length=64), nullable=True),
        sa.Column("venue", sa.Text(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("work_type", sa.String(length=64), nullable=False),
        sa.Column("canonical_metadata_source", sa.String(length=128), nullable=True),
        sa.Column("reading_status", sa.String(length=64), nullable=False),
        sa.Column("processing_error", sa.Text(), nullable=True),
        sa.Column("main_file_id", sa.Uuid(), nullable=True),
        sa.Column("queue_position", sa.Integer(), nullable=True),
        sa.Column("user_confirmed", sa.Boolean(), nullable=False),
        sa.Column(
            "confirmed_fields",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "keywords",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "topics",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("import_batch_id", sa.Uuid(), nullable=True),
        sa.Column("version_group_id", sa.Uuid(), nullable=True),
        sa.Column("citation_count", sa.Integer(), nullable=True),
        sa.Column("citation_count_source", sa.String(length=32), nullable=True),
        sa.Column("citation_count_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("citing_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("citing_fetched_source", sa.String(length=32), nullable=True),
        sa.Column("merged_into_id", sa.Uuid(), nullable=True),
        sa.Column(
            "merge_record",
            sa.JSON(none_as_null=True).with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["import_batch_id"], ["import_batches.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["main_file_id"], ["files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["merged_into_id"], ["works.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_works_arxiv_base_id"), "works", ["arxiv_base_id"], unique=False)
    op.create_index(op.f("ix_works_arxiv_id"), "works", ["arxiv_id"], unique=False)
    op.create_index(op.f("ix_works_canonical_title"), "works", ["canonical_title"], unique=False)
    op.create_index(
        op.f("ix_works_created_by_user_id"), "works", ["created_by_user_id"], unique=False
    )
    op.create_index(op.f("ix_works_doi"), "works", ["doi"], unique=False)
    op.create_index(op.f("ix_works_import_batch_id"), "works", ["import_batch_id"], unique=False)
    op.create_index(op.f("ix_works_merged_into_id"), "works", ["merged_into_id"], unique=False)
    op.create_index(op.f("ix_works_normalized_title"), "works", ["normalized_title"], unique=False)
    op.create_index(op.f("ix_works_queue_position"), "works", ["queue_position"], unique=False)
    op.create_index(op.f("ix_works_reading_status"), "works", ["reading_status"], unique=False)
    op.create_index(op.f("ix_works_version_group_id"), "works", ["version_group_id"], unique=False)
    op.create_index(op.f("ix_works_work_type"), "works", ["work_type"], unique=False)
    op.create_index(op.f("ix_works_year"), "works", ["year"], unique=False)
    op.create_table(
        "agent_files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("local_file_id", sa.String(length=255), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("display_path", sa.String(length=1024), nullable=True),
        sa.Column("virtual_path", sa.String(length=1024), nullable=True),
        sa.Column("mime_type", sa.String(length=128), nullable=True),
        sa.Column("import_action", sa.String(length=32), nullable=False),
        sa.Column("teleport_policy", sa.String(length=16), nullable=False),
        sa.Column("processing_state", sa.String(length=32), nullable=False),
        sa.Column("teleport_blocked", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("preview_text", sa.Text(), nullable=True),
        sa.Column("teleport_status", sa.String(length=32), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=True),
        sa.Column("work_id", sa.Uuid(), nullable=True),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["work_id"], ["works.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", "local_file_id", name="uq_agent_local_file"),
    )
    op.create_index(op.f("ix_agent_files_agent_id"), "agent_files", ["agent_id"], unique=False)
    op.create_index(
        op.f("ix_agent_files_local_file_id"), "agent_files", ["local_file_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_files_processing_state"), "agent_files", ["processing_state"], unique=False
    )
    op.create_index(op.f("ix_agent_files_sha256"), "agent_files", ["sha256"], unique=False)
    op.create_index(
        op.f("ix_agent_files_teleport_status"), "agent_files", ["teleport_status"], unique=False
    )
    op.create_index(op.f("ix_agent_files_work_id"), "agent_files", ["work_id"], unique=False)
    op.create_table(
        "external_papers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("dedup_key", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("doi", sa.String(length=255), nullable=True),
        sa.Column("arxiv_id", sa.String(length=64), nullable=True),
        sa.Column("resolved_work_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("authors", sa.Text(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("venue", sa.Text(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["resolved_work_id"], ["works.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_external_papers_dedup_key"), "external_papers", ["dedup_key"], unique=True
    )
    op.create_index(op.f("ix_external_papers_doi"), "external_papers", ["doi"], unique=False)
    op.create_index(
        op.f("ix_external_papers_resolved_work_id"),
        "external_papers",
        ["resolved_work_id"],
        unique=False,
    )
    op.create_table(
        "references",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("resolved_work_id", sa.Uuid(), nullable=True),
        sa.Column("suggested_work_id", sa.Uuid(), nullable=True),
        sa.Column("match_score", sa.Float(), nullable=True),
        sa.Column("raw_citation", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("normalized_title", sa.Text(), nullable=True),
        sa.Column("doi", sa.String(length=255), nullable=True),
        sa.Column("arxiv_id", sa.String(length=64), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column(
            "authors",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("dedup_key", sa.String(length=512), nullable=True),
        sa.Column("resolution_status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["resolved_work_id"], ["works.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["suggested_work_id"], ["works.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_references_arxiv_id"), "references", ["arxiv_id"], unique=False)
    op.create_index(op.f("ix_references_dedup_key"), "references", ["dedup_key"], unique=False)
    op.create_index(op.f("ix_references_doi"), "references", ["doi"], unique=False)
    op.create_index(
        op.f("ix_references_normalized_title"), "references", ["normalized_title"], unique=False
    )
    op.create_index(
        op.f("ix_references_resolution_status"), "references", ["resolution_status"], unique=False
    )
    op.create_index(
        op.f("ix_references_resolved_work_id"), "references", ["resolved_work_id"], unique=False
    )
    op.create_index(
        op.f("ix_references_suggested_work_id"), "references", ["suggested_work_id"], unique=False
    )
    op.create_table(
        "shelf_works",
        sa.Column("shelf_id", sa.Uuid(), nullable=False),
        sa.Column("work_id", sa.Uuid(), nullable=False),
        sa.Column("added_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["shelf_id"], ["shelves.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["work_id"], ["works.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("shelf_id", "work_id"),
    )
    op.create_index(
        op.f("ix_shelf_works_added_by_user_id"), "shelf_works", ["added_by_user_id"], unique=False
    )
    op.create_index(op.f("ix_shelf_works_work_id"), "shelf_works", ["work_id"], unique=False)
    op.create_table(
        "work_chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("work_id", sa.Uuid(), nullable=False),
        sa.Column("section", sa.String(length=255), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["work_id"], ["works.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("work_id", "position", name="uq_work_chunk_position"),
    )
    op.create_index(op.f("ix_work_chunks_work_id"), "work_chunks", ["work_id"], unique=False)
    op.create_table(
        "work_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("work_a_id", sa.Uuid(), nullable=False),
        sa.Column("work_b_id", sa.Uuid(), nullable=False),
        sa.Column("link_type", sa.String(length=32), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["work_a_id"], ["works.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["work_b_id"], ["works.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("work_a_id", "work_b_id", "link_type", name="uq_work_link_pair"),
    )
    op.create_index(
        op.f("ix_work_links_created_by_user_id"), "work_links", ["created_by_user_id"], unique=False
    )
    op.create_index(op.f("ix_work_links_work_a_id"), "work_links", ["work_a_id"], unique=False)
    op.create_index(op.f("ix_work_links_work_b_id"), "work_links", ["work_b_id"], unique=False)
    op.create_table(
        "work_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("work_id", sa.Uuid(), nullable=False),
        sa.Column("version_label", sa.String(length=128), nullable=True),
        sa.Column("source", sa.String(length=128), nullable=True),
        sa.Column("publication_state", sa.String(length=64), nullable=True),
        sa.Column("version_type", sa.String(length=64), nullable=False),
        sa.Column("arxiv_version", sa.String(length=32), nullable=True),
        sa.Column("doi", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["work_id"], ["works.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_work_versions_doi"), "work_versions", ["doi"], unique=False)
    op.create_index(op.f("ix_work_versions_work_id"), "work_versions", ["work_id"], unique=False)
    op.create_table(
        "citation_mentions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("citing_work_id", sa.Uuid(), nullable=False),
        sa.Column("reference_id", sa.Uuid(), nullable=False),
        sa.Column("resolved_cited_work_id", sa.Uuid(), nullable=True),
        sa.Column("marker_text", sa.String(length=128), nullable=True),
        sa.Column("section_label", sa.String(length=255), nullable=True),
        sa.Column("context_before", sa.Text(), nullable=True),
        sa.Column("context_sentence", sa.Text(), nullable=True),
        sa.Column("context_after", sa.Text(), nullable=True),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column(
            "pdf_coordinates",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("source_tei_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["citing_work_id"], ["works.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reference_id"], ["references.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["resolved_cited_work_id"], ["works.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_tei_id"], ["raw_tei_documents.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_citation_mentions_citing_work_id"),
        "citation_mentions",
        ["citing_work_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_citation_mentions_reference_id"),
        "citation_mentions",
        ["reference_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_citation_mentions_resolved_cited_work_id"),
        "citation_mentions",
        ["resolved_cited_work_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_citation_mentions_source_tei_id"),
        "citation_mentions",
        ["source_tei_id"],
        unique=False,
    )
    op.create_table(
        "external_citation_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("external_paper_id", sa.Uuid(), nullable=False),
        sa.Column("work_id", sa.Uuid(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["external_paper_id"], ["external_papers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["work_id"], ["works.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_paper_id", "work_id", name="uq_external_citation_link"),
    )
    op.create_index(
        op.f("ix_external_citation_links_external_paper_id"),
        "external_citation_links",
        ["external_paper_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_citation_links_work_id"),
        "external_citation_links",
        ["work_id"],
        unique=False,
    )
    op.create_table(
        "file_work_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("work_id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=True),
        sa.Column("segment_id", sa.Uuid(), nullable=True),
        sa.Column("relationship_type", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("warning_state", sa.String(length=128), nullable=False),
        sa.Column("user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["segment_id"], ["file_segments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["version_id"], ["work_versions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["work_id"], ["works.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_file_work_links_file_id"), "file_work_links", ["file_id"], unique=False
    )
    op.create_index(
        op.f("ix_file_work_links_segment_id"), "file_work_links", ["segment_id"], unique=False
    )
    op.create_index(
        op.f("ix_file_work_links_version_id"), "file_work_links", ["version_id"], unique=False
    )
    op.create_index(
        op.f("ix_file_work_links_work_id"), "file_work_links", ["work_id"], unique=False
    )
    op.create_table(
        "reference_citations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reference_id", sa.Uuid(), nullable=False),
        sa.Column("citing_work_id", sa.Uuid(), nullable=False),
        sa.Column("source_tei_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["citing_work_id"], ["works.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reference_id"], ["references.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_tei_id"], ["raw_tei_documents.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reference_id", "citing_work_id", name="uq_reference_citation"),
    )
    op.create_index(
        op.f("ix_reference_citations_citing_work_id"),
        "reference_citations",
        ["citing_work_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reference_citations_reference_id"),
        "reference_citations",
        ["reference_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reference_citations_source_tei_id"),
        "reference_citations",
        ["source_tei_id"],
        unique=False,
    )
