"""convert datetime columns to timestamptz

Revision ID: 6a310e33c3d6
Revises: 0007_annotations
Create Date: 2026-06-25 12:59:00.100062+00:00

Hand-written (the autogenerated draft was discarded: it had bundled in unrelated and
destructive changes — dropping every foreign key, a JSONB->JSON downgrade, and table
creates). This migration does one thing: convert naive ``timestamp`` columns to
``timestamptz``, interpreting the stored naive values as UTC (which is what the app writes
via ``datetime.now(UTC)``). It introspects the schema so it covers every datetime column,
and is a no-op on SQLite (which has no real timezone support).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6a310e33c3d6"
down_revision: str | None = "0007_annotations"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _columns_of_type(data_type: str) -> list[tuple[str, str]]:
    """Return (table, column) for every public column of the given catalog ``data_type``.

    Queried straight from ``information_schema`` (not the ORM inspector, whose per-table cache
    goes stale across the ALTERs we issue), so detection is deterministic and complete.
    """
    rows = (
        op.get_bind()
        .execute(
            sa.text(
                "SELECT table_name, column_name FROM information_schema.columns "
                "WHERE table_schema = 'public' AND data_type = :dtype "
                "ORDER BY table_name, column_name"
            ),
            {"dtype": data_type},
        )
        .all()
    )
    return [(table, column) for table, column in rows]


def upgrade() -> None:
    """Convert naive timestamp columns to timestamptz (interpreting stored values as UTC)."""
    if op.get_bind().dialect.name != "postgresql":
        return
    for table, column in _columns_of_type("timestamp without time zone"):
        op.execute(
            sa.text(
                f'ALTER TABLE "{table}" ALTER COLUMN "{column}" '
                f"TYPE timestamptz USING \"{column}\" AT TIME ZONE 'UTC'"
            )
        )


def downgrade() -> None:
    """Convert timestamptz columns back to naive timestamp (values expressed in UTC)."""
    if op.get_bind().dialect.name != "postgresql":
        return
    for table, column in _columns_of_type("timestamp with time zone"):
        op.execute(
            sa.text(
                f'ALTER TABLE "{table}" ALTER COLUMN "{column}" '
                f"TYPE timestamp USING \"{column}\" AT TIME ZONE 'UTC'"
            )
        )
