#!/usr/bin/env bash
# Install a plain git pre-commit hook that runs the PaRacORD secret scanner.
# Use this when you do not want the `pre-commit` framework — no extra dependencies.
#
#   bash scripts/install_git_hooks.sh
#
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
hook_dir="$repo_root/.git/hooks"
hook_path="$hook_dir/pre-commit"

mkdir -p "$hook_dir"

cat > "$hook_path" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install_git_hooks.sh — runs the PaRacORD secret scan.
set -euo pipefail
repo_root="$(git rev-parse --show-toplevel)"
python "$repo_root/scripts/check_secrets.py"
HOOK

chmod +x "$hook_path"
echo "Installed pre-commit secret scan at $hook_path"
