// GENERATED by scripts/build-themes.mjs from frontend/themes/*.yaml — DO NOT EDIT.
// Edit the YAML source and run `npm run themes:build`.

import type { Theme } from './types';

export const bundledThemes: Theme[] = [
  {
    "id": "default-dark",
    "name": "Default (dark)",
    "mode": "dark",
    "temperature": "cool",
    "tokens": {
      "surface": {
        "base": "#141a21",
        "raised": "#1b232c",
        "overlay": "#1b232c",
        "sunken": "#141a21",
        "hover": "#1b232c"
      },
      "ink": {
        "strong": "#e6edf3",
        "normal": "#e6edf3",
        "muted": "#a8b3bf",
        "inverse": "#141a21"
      },
      "border": {
        "normal": "#3a4650",
        "strong": "#3a4650",
        "focus": "#64b5cd"
      },
      "accent": {
        "primary": "#4c72b0",
        "primary-strong": "#64b5cd",
        "secondary": "#a8b3bf",
        "link": "#64b5cd"
      },
      "status": {
        "success": "#55a868",
        "warning": "#ccb974",
        "danger": "#c44e52",
        "info": "#64b5cd"
      },
      "radius": {
        "sm": "6px",
        "md": "8px"
      },
      "font": {
        "family": "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif"
      }
    },
    "graph": {
      "surface": "#141a21",
      "text": "#e6edf3",
      "axis_line": "#3a4650",
      "split_line": "#232c35",
      "tooltip_bg": "#e6edf3",
      "tooltip_text": "#141a21",
      "font": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
      "categorical": [
        "#4c72b0",
        "#dd8452",
        "#55a868",
        "#c44e52",
        "#8172b3",
        "#937860",
        "#da8bc3",
        "#8c8c8c",
        "#ccb974",
        "#64b5cd"
      ]
    }
  },
  {
    "id": "default",
    "name": "Default (light)",
    "mode": "light",
    "temperature": "cool",
    "tokens": {
      "surface": {
        "base": "#eef1f4",
        "raised": "#fbfcfd",
        "overlay": "#ffffff",
        "sunken": "#f4f6f9",
        "hover": "#eef2f6"
      },
      "ink": {
        "strong": "#1f2a36",
        "normal": "#203142",
        "muted": "#64717f",
        "inverse": "#ffffff"
      },
      "border": {
        "normal": "#cbd5e1",
        "strong": "#d8dee6",
        "focus": "#2563eb"
      },
      "accent": {
        "primary": "#2d3e50",
        "primary-strong": "#1f2a36",
        "secondary": "#21303d",
        "link": "#2563eb"
      },
      "status": {
        "success": "#166534",
        "warning": "#b45309",
        "danger": "#b3261e",
        "info": "#1d4ed8"
      },
      "radius": {
        "sm": "6px",
        "md": "8px"
      },
      "font": {
        "family": "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif"
      }
    },
    "graph": {
      "surface": "#ffffff",
      "text": "#21303d",
      "axis_line": "#bcc7d2",
      "split_line": "#eef2f6",
      "tooltip_bg": "#1f2a36",
      "tooltip_text": "#ffffff",
      "font": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
      "categorical": [
        "#4c72b0",
        "#dd8452",
        "#55a868",
        "#c44e52",
        "#8172b3",
        "#937860",
        "#da8bc3",
        "#8c8c8c",
        "#ccb974",
        "#64b5cd"
      ]
    }
  }
];
